---
apiVersion: v1
kind: Secret
metadata:
  name: ephemeral-k8s-cloud-init
  labels:
    airshipit.org/stage: isogen
type: Opaque
stringData:
  userdata: |
    {{ getTreeByPath "airshipit.org_v1alpha1_UserData" "eph-user-data" "spec" }}
  netconfig: |
    network:
      version: 1
      config:
       - mac_address: {{ getTreeByPath "airshipit.org_v1alpha1_NodeNetInterface" "worker-node01" "spec.links.[0].ethernet_mac_address" }}
         type: physical
         name:  {{ getTreeByPath "airshipit.org_v1alpha1_NodeNetInterface" "worker-node01" "spec.links.[0].id" }}
         subnets:
           - type: static
             address: {{ getTreeByPath "airshipit.org_v1alpha1_NodeNetInterface" "worker-node01" "spec.networks.[0].ip_address" }}
             netmask: {{ getTreeByPath "airshipit.org_v1alpha1_NodeNetInterface" "worker-node01" "spec.networks.[0].netmask" }}
             gateway: {{ getTreeByPath "airshipit.org_v1alpha1_NodeNetInterface" "worker-node01" "spec.networks.[0].routes.[0].gateway" }}
             dns_nameservers:
               - {{ getTreeByPath "airshipit.org_v1alpha1_NodeNetInterface" "worker-node01" "spec.services.[0].address" }}
       - mac_address: {{ getTreeByPath "airshipit.org_v1alpha1_NodeNetInterface" "worker-node01" "spec.links.[1].ethernet_mac_address" }}
         type: physical
         name:  {{ getTreeByPath "airshipit.org_v1alpha1_NodeNetInterface" "worker-node01" "spec.links.[1].id" }}
         subnets:
           - type: static
             address: {{ getTreeByPath "airshipit.org_v1alpha1_NodeNetInterface" "worker-node01" "spec.networks.[1].ip_address" }}
             netmask: {{ getTreeByPath "airshipit.org_v1alpha1_NodeNetInterface" "worker-node01" "spec.networks.[1].netmask" }}
